# Generated by Django 3.0.2 on 2020-01-29 22:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name="Nom de l'album")),
                ('publicationDate', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Album photo',
                'ordering': ['-publicationDate'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracknumber', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ordre')),
                ('songname', models.CharField(max_length=150, verbose_name='Titre')),
                ('songfile', models.FileField(upload_to='audio', verbose_name='Fichier')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Fichiers audio',
                'ordering': ['tracknumber'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('isPublished', models.BooleanField(default=False, verbose_name='Visible')),
                ('publicationDate', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('creationDate', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('modificationDate', models.DateTimeField(editable=False, null=True, verbose_name='Dernière modification')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Publications',
                'ordering': ['-creationDate'],
            },
        ),
        migrations.CreateModel(
            name='PrestationCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie Prestation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artist_website.Item')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Où')),
                ('eventDate', models.CharField(blank=True, max_length=250, null=True, verbose_name='Quand')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='event_picture')),
            ],
            options={
                'verbose_name': 'Évènement',
                'ordering': ['-publicationDate'],
            },
            bases=('artist_website.item',),
        ),
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artist_website.Item')),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['title'],
            },
            bases=('artist_website.item',),
        ),
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artist_website.Item')),
                ('date', models.CharField(blank=True, max_length=250, null=True, verbose_name='Date de parution')),
                ('source', models.CharField(blank=True, max_length=500, null=True, verbose_name='Source')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='article_picture')),
            ],
            options={
                'verbose_name': 'Article de presse',
                'verbose_name_plural': 'Articles de presse',
                'ordering': ['-publicationDate'],
            },
            bases=('artist_website.item',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gallery')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='artist_website.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artist_website.Item')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_website.PrestationCat')),
            ],
            options={
                'verbose_name': 'Prestation',
                'ordering': ['-creationDate'],
            },
            bases=('artist_website.item',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artist_website.Item')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_website.Category')),
            ],
            options={
                'verbose_name': 'Page',
                'ordering': ['-creationDate'],
            },
            bases=('artist_website.item',),
        ),
    ]
