# Generated by Django 3.0.2 on 2020-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='length',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Durée'),
        ),
    ]
