# Generated by Django 3.0.2 on 2020-02-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_website', '0002_audiofile_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photograph',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='photographe'),
        ),
        migrations.AddField(
            model_name='album',
            name='photographWebsite',
            field=models.URLField(blank=True, null=True, verbose_name='site du photographe'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titre',
            field=models.CharField(max_length=100, verbose_name="Nom de l'album"),
        ),
    ]
